"""add batch identity constraint

Revision ID: 4e16d47e3a45
Revises: f9edff16ea76
Create Date: 2026-09-23 22:25:17.048880

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e16d47e3a45"
down_revision: str | Sequence[str] | None = "f9edff16ea76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_batches_product_location_number",
        "batches",
        ["product_id", "location_id", "batch_number"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_batches_product_location_number", "batches", type_="unique")
    # ### end Alembic commands ###
