"""add forecast supply data

Revision ID: 981ba10392c3
Revises: 4e16d47e3a45
Create Date: 2026-09-27 04:25:32.734192

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "981ba10392c3"
down_revision: str | Sequence[str] | None = "4e16d47e3a45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("document_number", sa.String(length=128), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("expected_at", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IN_TRANSIT",
                "RECEIVED",
                "CANCELLED",
                name="supply_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name="ck_purchase_orders_quantity_positive",
        ),
        sa.CheckConstraint(
            "unit_price >= 0",
            name="ck_purchase_orders_unit_price_nonnegative",
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"]),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_number",
            name="uq_purchase_orders_document_number",
        ),
    )
    op.create_index(
        "ix_purchase_orders_forecast_lookup",
        "purchase_orders",
        ["product_id", "location_id", "status", "expected_at"],
        unique=False,
    )
    op.add_column(
        "products",
        sa.Column(
            "lead_time_days",
            sa.Integer(),
            server_default=sa.text("7"),
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "package_size",
            sa.Numeric(precision=14, scale=3),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "min_order_quantity",
            sa.Numeric(precision=14, scale=3),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    op.alter_column("products", "lead_time_days", server_default=None)
    op.alter_column("products", "package_size", server_default=None)
    op.alter_column("products", "min_order_quantity", server_default=None)
    op.create_check_constraint(
        "ck_products_lead_time_days_nonnegative",
        "products",
        "lead_time_days >= 0",
    )
    op.create_check_constraint(
        "ck_products_package_size_positive",
        "products",
        "package_size > 0",
    )
    op.create_check_constraint(
        "ck_products_min_order_quantity_positive",
        "products",
        "min_order_quantity > 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_products_min_order_quantity_positive",
        "products",
        type_="check",
    )
    op.drop_constraint(
        "ck_products_package_size_positive",
        "products",
        type_="check",
    )
    op.drop_constraint(
        "ck_products_lead_time_days_nonnegative",
        "products",
        type_="check",
    )
    op.drop_column("products", "min_order_quantity")
    op.drop_column("products", "package_size")
    op.drop_column("products", "lead_time_days")
    op.drop_index(
        "ix_purchase_orders_forecast_lookup",
        table_name="purchase_orders",
    )
    op.drop_table("purchase_orders")
    sa.Enum(name="supply_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
