"""add batch number

Revision ID: f9edff16ea76
Revises: 14affa637442
Create Date: 2026-09-23 21:59:28.240213

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9edff16ea76"
down_revision: str | Sequence[str] | None = "14affa637442"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "batches", sa.Column("batch_number", sa.String(length=64), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("batches", "batch_number")
    # ### end Alembic commands ###
